### ISSUE TITLE
Taskbar

### ISSUE THREAD

**Issue by anjelica-m** [CMPUT301W23T43/BARQR#27]
Implement the taskbar that will be on multiple views of the app.

### VIEWS
* MAIN
* ...

### Completion Criteria:

Must have Buttons for 

- [x] Add new code
- [x] Leaderboard
- [x] Map
- [x] Account
- [x] Home

- [x] Must be visible on appropriate screens
- [x] Buttons must be clickable
- [x] Buttons must do assigned function

**Comment by tjpollom** [comment]
This is implemented fully now.
